name: lemmy-help

on: [push]

env:
  PLUGIN_NAME: open

jobs:
  docs:
    runs-on: ubuntu-latest
    name: emmylua to vimdoc
    steps:
      - uses: actions/checkout@v2

      - name: Generating help
        run: |
          curl -Lq https://github.com/numToStr/lemmy-help/releases/latest/download/lemmy-help-x86_64-unknown-linux-gnu.tar.gz | tar xz
          ./lemmy-help --prefix-func --prefix-alias --prefix-class --prefix-type lua/open/init.lua lua/open/openers/init.lua $(ls lua/open/openers/ | grep -v init.lua| xargs -I{} echo lua/open/openers/{} | xargs) > doc/${{env.PLUGIN_NAME}}.txt

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ github.head_ref }}
          commit_message: "chore(docs): auto-generate vimdoc"
          file_pattern: doc/*.txt
